In [2]:
import pandas as pd 

df = pd.read_excel('india_DA_full_rawdata.xlsx')
df.head()

,job_title,employer_name,job_publisher,job_employment_type,Job_aplication_procedure,job_description,job_is_remote,job_posted_at_datetime_utc,job_location,job_city,job_state
0,Data Analyst Lead - Python / SQL / Advance Exc...,Jero Technologies,Shine,Full–time,Through Publisher,"- Robust Excel skills (functions, pivot tables...",False,2026-07-22T02:00:00.000Z,India,NaN,NaN
1,"Data Analyst Fresher , Data Analytics",Apex Engineering Solutions,BeBee,Full–time,Through Publisher,Job description\n\nWe are looking for Data Ana...,False,2026-07-20T00:00:00.000Z,India,NaN,NaN
2,Senior Data Analyst,Walr,Walr,Full–time,Through Publisher,Why Walr?\nWalr is the service-first data coll...,False,2026-07-20T00:00:00.000Z,"Kora, Maharashtra",Kora,Maharashtra
3,Data Analyst – AVP,1203 Barclays Global Serv. Cent,Workday,Full–time,Through Publisher,Job Description Purpose of the role To enable ...,False,2026-07-20T00:00:00.000Z,India,NaN,NaN
4,Data Analyst Intern,CLUSTOR COMPUTING,Shine,Full–time,Through Publisher,About the Company\n\nClustor Computing is an i...,False,2026-07-20T00:00:00.000Z,"Nagpur, Maharashtra",Nagpur,Maharashtra

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 147 entries, 0 to 146
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   job_title                   147 non-null    object
 1   employer_name               147 non-null    object
 2   job_publisher               147 non-null    object
 3   job_employment_type         147 non-null    object
 4   Job_aplication_procedure    147 non-null    object
 5   job_description             147 non-null    object
 6   job_is_remote               147 non-null    bool
 7   job_posted_at_datetime_utc  97 non-null     object
 8   job_location                147 non-null    object
 9   job_city                    5 non-null      object
 10  job_state                   5 non-null      object
dtypes: bool(1), object(10)
memory usage: 11.8+ KB

In [4]:
df.describe()

,job_title,employer_name,job_publisher,job_employment_type,Job_aplication_procedure,job_description,job_is_remote,job_posted_at_datetime_utc,job_location,job_city,job_state
count,147,147,147,147,147,147,147,97,147,5,5
unique,144,122,15,4,1,145,2,26,4,2,1
top,Master Data Analyst - Cellasto,remotepromsp,Shine,Full–time,Through Publisher,"Collect, clean, and validate data from multipl...",False,2026-07-20T00:00:00.000Z,India,Nagpur,Maharashtra
freq,2,10,84,144,147,2,135,11,130,4,5

In [5]:
df.duplicated().sum()

np.int64(2)

In [6]:
df.isnull().sum()

job_title                       0
employer_name                   0
job_publisher                   0
job_employment_type             0
Job_aplication_procedure        0
job_description                 0
job_is_remote                   0
job_posted_at_datetime_utc     50
job_location                    0
job_city                      142
job_state                     142
dtype: int64

In [7]:
df.shape

(147, 11)

In [8]:
df.head()

,job_title,employer_name,job_publisher,job_employment_type,Job_aplication_procedure,job_description,job_is_remote,job_posted_at_datetime_utc,job_location,job_city,job_state
0,Data Analyst Lead - Python / SQL / Advance Exc...,Jero Technologies,Shine,Full–time,Through Publisher,"- Robust Excel skills (functions, pivot tables...",False,2026-07-22T02:00:00.000Z,India,NaN,NaN
1,"Data Analyst Fresher , Data Analytics",Apex Engineering Solutions,BeBee,Full–time,Through Publisher,Job description\n\nWe are looking for Data Ana...,False,2026-07-20T00:00:00.000Z,India,NaN,NaN
2,Senior Data Analyst,Walr,Walr,Full–time,Through Publisher,Why Walr?\nWalr is the service-first data coll...,False,2026-07-20T00:00:00.000Z,"Kora, Maharashtra",Kora,Maharashtra
3,Data Analyst – AVP,1203 Barclays Global Serv. Cent,Workday,Full–time,Through Publisher,Job Description Purpose of the role To enable ...,False,2026-07-20T00:00:00.000Z,India,NaN,NaN
4,Data Analyst Intern,CLUSTOR COMPUTING,Shine,Full–time,Through Publisher,About the Company\n\nClustor Computing is an i...,False,2026-07-20T00:00:00.000Z,"Nagpur, Maharashtra",Nagpur,Maharashtra

In [9]:
df['job_title_clean'] = df['job_title'].astype(str).str.strip()

In [12]:
df['job_title_clean'] = df['job_title_clean'].str.strip().replace(r'\s+', ' ', regex=True) \
                                         .str.replace('...', '', regex=False) \
                                         .str.strip() \
                                         .str.title()
df['job_title_clean'].head()

0    Data Analyst Lead - Python / Sql / Advance Exc...
1                Data Analyst Fresher , Data Analytics
2                                  Senior Data Analyst
3                                   Data Analyst – Avp
4                                  Data Analyst Intern
Name: job_title_clean, dtype: object

In [13]:
df['job_title_clean'] = df['job_title_clean'].str.split('-').str[0]
df['job_title_clean'] = df['job_title_clean'].str.split('/').str[0]
df['job_title_clean'] = df['job_title_clean'].str.split(',').str[0]

In [14]:
df['job_title_clean'].head()

0       Data Analyst Lead
1    Data Analyst Fresher
2      Senior Data Analyst
3       Data Analyst – Avp
4      Data Analyst Intern
Name: job_title_clean, dtype: object

In [15]:
def std(t):
    t = t.lower()
    if 'intern' in t:
        return 'Intern'
    if 'fresher' in t:
        return 'Fresher'
    if 'senior' in t or 'lead' in t or 'avp' in t:
        return 'Senior / Lead'
    return 'Data Analyst'

df['job_level'] = df['job_title_clean'].apply(std)
df['job_level'].value_counts()

job_level
Data Analyst     110
Senior / Lead     24
Intern            10
Fresher            3
Name: count, dtype: int64

In [16]:
df.head()

,job_title,employer_name,job_publisher,job_employment_type,Job_aplication_procedure,job_description,job_is_remote,job_posted_at_datetime_utc,job_location,job_city,job_state,job_title_clean,job_level
0,Data Analyst Lead - Python / SQL / Advance Exc...,Jero Technologies,Shine,Full–time,Through Publisher,"- Robust Excel skills (functions, pivot tables...",False,2026-07-22T02:00:00.000Z,India,NaN,NaN,Data Analyst Lead,Senior / Lead
1,"Data Analyst Fresher , Data Analytics",Apex Engineering Solutions,BeBee,Full–time,Through Publisher,Job description\n\nWe are looking for Data Ana...,False,2026-07-20T00:00:00.000Z,India,NaN,NaN,Data Analyst Fresher,Fresher
2,Senior Data Analyst,Walr,Walr,Full–time,Through Publisher,Why Walr?\nWalr is the service-first data coll...,False,2026-07-20T00:00:00.000Z,"Kora, Maharashtra",Kora,Maharashtra,Senior Data Analyst,Senior / Lead
3,Data Analyst – AVP,1203 Barclays Global Serv. Cent,Workday,Full–time,Through Publisher,Job Description Purpose of the role To enable ...,False,2026-07-20T00:00:00.000Z,India,NaN,NaN,Data Analyst – Avp,Senior / Lead
4,Data Analyst Intern,CLUSTOR COMPUTING,Shine,Full–time,Through Publisher,About the Company\n\nClustor Computing is an i...,False,2026-07-20T00:00:00.000Z,"Nagpur, Maharashtra",Nagpur,Maharashtra,Data Analyst Intern,Intern

In [17]:
df['job_title']

0      Data Analyst Lead - Python / SQL / Advance Exc...
1                  Data Analyst Fresher , Data Analytics
2                                    Senior Data Analyst
3                                     Data Analyst – AVP
4                                    Data Analyst Intern
                             ...
142                     Agricultural Data Analyst Intern
143                    Data Analyst (Data Product Owner)
144                Healthcare Data Analyst Intern Remote
145    Finance Data Analyst  Remote Contract Opportun...
146                                Clinical Data Analyst
Name: job_title, Length: 147, dtype: object

In [20]:
df['job_title_clean'] = df['job_title_clean'].str.split('&').str[0]

In [21]:
df['job_title_clean'] = df['job_title_clean'].str.split('|').str[0]

In [25]:
df['job_title_clean'] = df['job_title_clean'].str.strip().str.title()

In [26]:
df['job_title_clean'].head()

0       Data Analyst Lead
1    Data Analyst Fresher
2     Senior Data Analyst
3      Data Analyst – Avp
4     Data Analyst Intern
Name: job_title_clean, dtype: object

In [27]:
df.head()

,job_title,employer_name,job_publisher,job_employment_type,Job_aplication_procedure,job_description,job_is_remote,job_posted_at_datetime_utc,job_location,job_city,job_state,job_title_clean,job_level
0,Data Analyst Lead - Python / SQL / Advance Exc...,Jero Technologies,Shine,Full–time,Through Publisher,"- Robust Excel skills (functions, pivot tables...",False,2026-07-22T02:00:00.000Z,India,NaN,NaN,Data Analyst Lead,Senior / Lead
1,"Data Analyst Fresher , Data Analytics",Apex Engineering Solutions,BeBee,Full–time,Through Publisher,Job description\n\nWe are looking for Data Ana...,False,2026-07-20T00:00:00.000Z,India,NaN,NaN,Data Analyst Fresher,Fresher
2,Senior Data Analyst,Walr,Walr,Full–time,Through Publisher,Why Walr?\nWalr is the service-first data coll...,False,2026-07-20T00:00:00.000Z,"Kora, Maharashtra",Kora,Maharashtra,Senior Data Analyst,Senior / Lead
3,Data Analyst – AVP,1203 Barclays Global Serv. Cent,Workday,Full–time,Through Publisher,Job Description Purpose of the role To enable ...,False,2026-07-20T00:00:00.000Z,India,NaN,NaN,Data Analyst – Avp,Senior / Lead
4,Data Analyst Intern,CLUSTOR COMPUTING,Shine,Full–time,Through Publisher,About the Company\n\nClustor Computing is an i...,False,2026-07-20T00:00:00.000Z,"Nagpur, Maharashtra",Nagpur,Maharashtra,Data Analyst Intern,Intern

In [28]:
df.iloc[142]

job_title                                      Agricultural Data Analyst Intern
employer_name                                              Sea6 Energy Pvt Ltd.
job_publisher                                                             Shine
job_employment_type                                                   Full–time
Job_aplication_procedure                                      Through Publisher
job_description               As a Junior Research Scientist at our company,...
job_is_remote                                                             False
job_posted_at_datetime_utc                                                  NaN
job_location                                                              India
job_city                                                                    NaN
job_state                                                                   NaN
job_title_clean                                Agricultural Data Analyst Intern
job_level                                                                Intern
Name: 142, dtype: object

In [32]:
def get_domain(t):
    t = t.lower()
    if 'agricultural' in t:
        return 'Agriculture'
    if 'health' in t or 'clinical' in t:
        return 'Healthcare'
    if 'finance' in t or 'fintech' in t or 'bank' in t:
        return 'Finance'
    if 'marketing' in t or 'sales' in t:
        return 'Marketing'
    if 'hr' in t or 'human resource' in t:
        return 'HR'
    if 'ecommerce' in t or 'retail' in t:
        return 'ECommerce / Retail'
    return 'General / IT'

df['job_domain'] = df['job_title'].apply(get_domain)
df['job_domain'].value_counts()

job_domain
General / IT          130
Marketing               8
HR                      3
Healthcare              3
ECommerce / Retail      1
Agriculture             1
Finance                 1
Name: count, dtype: int64

In [33]:
df.head()

,job_title,employer_name,job_publisher,job_employment_type,Job_aplication_procedure,job_description,job_is_remote,job_posted_at_datetime_utc,job_location,job_city,job_state,job_title_clean,job_level,job_domain
0,Data Analyst Lead - Python / SQL / Advance Exc...,Jero Technologies,Shine,Full–time,Through Publisher,"- Robust Excel skills (functions, pivot tables...",False,2026-07-22T02:00:00.000Z,India,NaN,NaN,Data Analyst Lead,Senior / Lead,General / IT
1,"Data Analyst Fresher , Data Analytics",Apex Engineering Solutions,BeBee,Full–time,Through Publisher,Job description\n\nWe are looking for Data Ana...,False,2026-07-20T00:00:00.000Z,India,NaN,NaN,Data Analyst Fresher,Fresher,General / IT
2,Senior Data Analyst,Walr,Walr,Full–time,Through Publisher,Why Walr?\nWalr is the service-first data coll...,False,2026-07-20T00:00:00.000Z,"Kora, Maharashtra",Kora,Maharashtra,Senior Data Analyst,Senior / Lead,General / IT
3,Data Analyst – AVP,1203 Barclays Global Serv. Cent,Workday,Full–time,Through Publisher,Job Description Purpose of the role To enable ...,False,2026-07-20T00:00:00.000Z,India,NaN,NaN,Data Analyst – Avp,Senior / Lead,General / IT
4,Data Analyst Intern,CLUSTOR COMPUTING,Shine,Full–time,Through Publisher,About the Company\n\nClustor Computing is an i...,False,2026-07-20T00:00:00.000Z,"Nagpur, Maharashtra",Nagpur,Maharashtra,Data Analyst Intern,Intern,General / IT

In [35]:
df['job_title'] = df['job_title_clean']
df = df.drop(columns=['job_title_clean'])
df['job_domain'].value_counts()

job_domain
General / IT          130
Marketing               8
HR                      3
Healthcare              3
ECommerce / Retail      1
Agriculture             1
Finance                 1
Name: count, dtype: int64

In [36]:
df.head()

,job_title,employer_name,job_publisher,job_employment_type,Job_aplication_procedure,job_description,job_is_remote,job_posted_at_datetime_utc,job_location,job_city,job_state,job_level,job_domain
0,Data Analyst Lead,Jero Technologies,Shine,Full–time,Through Publisher,"- Robust Excel skills (functions, pivot tables...",False,2026-07-22T02:00:00.000Z,India,NaN,NaN,Senior / Lead,General / IT
1,Data Analyst Fresher,Apex Engineering Solutions,BeBee,Full–time,Through Publisher,Job description\n\nWe are looking for Data Ana...,False,2026-07-20T00:00:00.000Z,India,NaN,NaN,Fresher,General / IT
2,Senior Data Analyst,Walr,Walr,Full–time,Through Publisher,Why Walr?\nWalr is the service-first data coll...,False,2026-07-20T00:00:00.000Z,"Kora, Maharashtra",Kora,Maharashtra,Senior / Lead,General / IT
3,Data Analyst – Avp,1203 Barclays Global Serv. Cent,Workday,Full–time,Through Publisher,Job Description Purpose of the role To enable ...,False,2026-07-20T00:00:00.000Z,India,NaN,NaN,Senior / Lead,General / IT
4,Data Analyst Intern,CLUSTOR COMPUTING,Shine,Full–time,Through Publisher,About the Company\n\nClustor Computing is an i...,False,2026-07-20T00:00:00.000Z,"Nagpur, Maharashtra",Nagpur,Maharashtra,Intern,General / IT

In [37]:
df['employer_name'] = df['employer_name'].astype(str).str.strip()

In [38]:
df['job_publisher'] = df['job_publisher'].astype(str).str.strip()

In [39]:
df['job_employment_type'] = df['job_employment_type'].astype(str).str.strip()

In [40]:
df['job_employment_type'].value_counts()

job_employment_type
Full–time                   144
Part-time                     1
Full–time and Internship      1
Internship                    1
Name: count, dtype: int64

In [43]:
full_text = ' '.join(df['job_description'].astype(str)).lower()
from collections import Counter
words = full_text.split()
common = Counter(words).most_common(50)
common

[('and', 4726),
 ('to', 2214),
 ('data', 1918),
 ('-', 1427),
 ('the', 1398),
 ('a', 1325),
 ('in', 1314),
 ('of', 1195),
 ('with', 1166),
 ('•', 931),
 ('for', 852),
 ('or', 547),
 ('business', 533),
 ('experience', 463),
 ('company', 444),
 ('reputed', 428),
 ('is', 424),
 ('will', 403),
 ('you', 402),
 ('as', 382),
 ('our', 330),
 ('work', 301),
 ('on', 296),
 ('your', 284),
 ('we', 281),
 ('analytics', 281),
 ('skills', 280),
 ('support', 276),
 ('strong', 275),
 ('that', 271),
 ('role', 239),
 ('be', 236),
 ('this', 229),
 ('analytical', 226),
 ('analysis', 226),
 ('tools', 225),
 ('at', 224),
 ('team', 221),
 ('from', 210),
 ('&', 209),
 ('are', 205),
 ('key', 204),
 ('an', 203),
 ('analyst', 202),
 ('across', 201),
 ('ability', 198),
 ('*', 194),
 ('insights', 190),
 ('reporting', 181),
 ('working', 179)]

In [44]:
my_words =['python', 'sql', 'excel', 'power bi', 'tableau', 'reporting', 'dashboard', 'analytics', 'insights', 'working',
           'team', 'analysis', 'skills', 'support', 'strong', 'reputed', 'experience', 'analysis', 'role', 'work']

def pick_words(text):
    text = str(text).lower()
    found = [w.title() for w in my_words if w in text]
    return ", ".join(found)
df['job_description_keywords'] = df['job_description'].apply(pick_words)
df[['job_title', 'job_description_keywords']].head()

              job_title                           job_description_keywords
0     Data Analyst Lead  Python, Sql, Excel, Team, Skills, Strong, Expe...
1  Data Analyst Fresher  Python, Sql, Excel, Power Bi, Tableau, Reporti...
2   Senior Data Analyst  Python, Excel, Analytics, Insights, Working, T...
3    Data Analyst – Avp  Python, Excel, Power Bi, Reporting, Dashboard,...
4   Data Analyst Intern  Python, Sql, Excel, Power Bi, Tableau, Dashboa...

In [45]:
df.head()

,job_title,employer_name,job_publisher,job_employment_type,Job_aplication_procedure,job_description,job_is_remote,job_posted_at_datetime_utc,job_location,job_city,job_state,job_level,job_domain,job_description_keywords
0,Data Analyst Lead,Jero Technologies,Shine,Full–time,Through Publisher,"- Robust Excel skills (functions, pivot tables...",False,2026-07-22T02:00:00.000Z,India,NaN,NaN,Senior / Lead,General / IT,"Python, Sql, Excel, Team, Skills, Strong, Expe..."
1,Data Analyst Fresher,Apex Engineering Solutions,BeBee,Full–time,Through Publisher,Job description\n\nWe are looking for Data Ana...,False,2026-07-20T00:00:00.000Z,India,NaN,NaN,Fresher,General / IT,"Python, Sql, Excel, Power Bi, Tableau, Reporti..."
2,Senior Data Analyst,Walr,Walr,Full–time,Through Publisher,Why Walr?\nWalr is the service-first data coll...,False,2026-07-20T00:00:00.000Z,"Kora, Maharashtra",Kora,Maharashtra,Senior / Lead,General / IT,"Python, Excel, Analytics, Insights, Working, T..."
3,Data Analyst – Avp,1203 Barclays Global Serv. Cent,Workday,Full–time,Through Publisher,Job Description Purpose of the role To enable ...,False,2026-07-20T00:00:00.000Z,India,NaN,NaN,Senior / Lead,General / IT,"Python, Excel, Power Bi, Reporting, Dashboard,..."
4,Data Analyst Intern,CLUSTOR COMPUTING,Shine,Full–time,Through Publisher,About the Company\n\nClustor Computing is an i...,False,2026-07-20T00:00:00.000Z,"Nagpur, Maharashtra",Nagpur,Maharashtra,Intern,General / IT,"Python, Sql, Excel, Power Bi, Tableau, Dashboa..."

In [46]:
df = df.drop(columns=['job_description'])

In [47]:
df.head()

,job_title,employer_name,job_publisher,job_employment_type,Job_aplication_procedure,job_is_remote,job_posted_at_datetime_utc,job_location,job_city,job_state,job_level,job_domain,job_description_keywords
0,Data Analyst Lead,Jero Technologies,Shine,Full–time,Through Publisher,False,2026-07-22T02:00:00.000Z,India,NaN,NaN,Senior / Lead,General / IT,"Python, Sql, Excel, Team, Skills, Strong, Expe..."
1,Data Analyst Fresher,Apex Engineering Solutions,BeBee,Full–time,Through Publisher,False,2026-07-20T00:00:00.000Z,India,NaN,NaN,Fresher,General / IT,"Python, Sql, Excel, Power Bi, Tableau, Reporti..."
2,Senior Data Analyst,Walr,Walr,Full–time,Through Publisher,False,2026-07-20T00:00:00.000Z,"Kora, Maharashtra",Kora,Maharashtra,Senior / Lead,General / IT,"Python, Excel, Analytics, Insights, Working, T..."
3,Data Analyst – Avp,1203 Barclays Global Serv. Cent,Workday,Full–time,Through Publisher,False,2026-07-20T00:00:00.000Z,India,NaN,NaN,Senior / Lead,General / IT,"Python, Excel, Power Bi, Reporting, Dashboard,..."
4,Data Analyst Intern,CLUSTOR COMPUTING,Shine,Full–time,Through Publisher,False,2026-07-20T00:00:00.000Z,"Nagpur, Maharashtra",Nagpur,Maharashtra,Intern,General / IT,"Python, Sql, Excel, Power Bi, Tableau, Dashboa..."

In [48]:
df['job_posted_date'] = df['job_posted_at_datetime_utc'].astype(str).str.split('T').str[0]

In [49]:
df.head()

,job_title,employer_name,job_publisher,job_employment_type,Job_aplication_procedure,job_is_remote,job_posted_at_datetime_utc,job_location,job_city,job_state,job_level,job_domain,job_description_keywords,job_posted_date
0,Data Analyst Lead,Jero Technologies,Shine,Full–time,Through Publisher,False,2026-07-22T02:00:00.000Z,India,NaN,NaN,Senior / Lead,General / IT,"Python, Sql, Excel, Team, Skills, Strong, Expe...",2026-07-22
1,Data Analyst Fresher,Apex Engineering Solutions,BeBee,Full–time,Through Publisher,False,2026-07-20T00:00:00.000Z,India,NaN,NaN,Fresher,General / IT,"Python, Sql, Excel, Power Bi, Tableau, Reporti...",2026-07-20
2,Senior Data Analyst,Walr,Walr,Full–time,Through Publisher,False,2026-07-20T00:00:00.000Z,"Kora, Maharashtra",Kora,Maharashtra,Senior / Lead,General / IT,"Python, Excel, Analytics, Insights, Working, T...",2026-07-20
3,Data Analyst – Avp,1203 Barclays Global Serv. Cent,Workday,Full–time,Through Publisher,False,2026-07-20T00:00:00.000Z,India,NaN,NaN,Senior / Lead,General / IT,"Python, Excel, Power Bi, Reporting, Dashboard,...",2026-07-20
4,Data Analyst Intern,CLUSTOR COMPUTING,Shine,Full–time,Through Publisher,False,2026-07-20T00:00:00.000Z,"Nagpur, Maharashtra",Nagpur,Maharashtra,Intern,General / IT,"Python, Sql, Excel, Power Bi, Tableau, Dashboa...",2026-07-20

In [50]:
df = df.drop(columns=['job_posted_at_datetime_utc'])

In [51]:
df.head()

,job_title,employer_name,job_publisher,job_employment_type,Job_aplication_procedure,job_is_remote,job_location,job_city,job_state,job_level,job_domain,job_description_keywords,job_posted_date
0,Data Analyst Lead,Jero Technologies,Shine,Full–time,Through Publisher,False,India,NaN,NaN,Senior / Lead,General / IT,"Python, Sql, Excel, Team, Skills, Strong, Expe...",2026-07-22
1,Data Analyst Fresher,Apex Engineering Solutions,BeBee,Full–time,Through Publisher,False,India,NaN,NaN,Fresher,General / IT,"Python, Sql, Excel, Power Bi, Tableau, Reporti...",2026-07-20
2,Senior Data Analyst,Walr,Walr,Full–time,Through Publisher,False,"Kora, Maharashtra",Kora,Maharashtra,Senior / Lead,General / IT,"Python, Excel, Analytics, Insights, Working, T...",2026-07-20
3,Data Analyst – Avp,1203 Barclays Global Serv. Cent,Workday,Full–time,Through Publisher,False,India,NaN,NaN,Senior / Lead,General / IT,"Python, Excel, Power Bi, Reporting, Dashboard,...",2026-07-20
4,Data Analyst Intern,CLUSTOR COMPUTING,Shine,Full–time,Through Publisher,False,"Nagpur, Maharashtra",Nagpur,Maharashtra,Intern,General / IT,"Python, Sql, Excel, Power Bi, Tableau, Dashboa...",2026-07-20

In [57]:
df['job_posted_date'].dtype

dtype('O')

In [56]:
df['job_posted_date'] = pd.to_datetime(df['job_posted_date']).dt.date

In [58]:
df['job_posted_date'].dtype

dtype('O')

In [59]:
df.head()

,job_title,employer_name,job_publisher,job_employment_type,Job_aplication_procedure,job_is_remote,job_location,job_city,job_state,job_level,job_domain,job_description_keywords,job_posted_date
0,Data Analyst Lead,Jero Technologies,Shine,Full–time,Through Publisher,False,India,NaN,NaN,Senior / Lead,General / IT,"Python, Sql, Excel, Team, Skills, Strong, Expe...",2026-07-22
1,Data Analyst Fresher,Apex Engineering Solutions,BeBee,Full–time,Through Publisher,False,India,NaN,NaN,Fresher,General / IT,"Python, Sql, Excel, Power Bi, Tableau, Reporti...",2026-07-20
2,Senior Data Analyst,Walr,Walr,Full–time,Through Publisher,False,"Kora, Maharashtra",Kora,Maharashtra,Senior / Lead,General / IT,"Python, Excel, Analytics, Insights, Working, T...",2026-07-20
3,Data Analyst – Avp,1203 Barclays Global Serv. Cent,Workday,Full–time,Through Publisher,False,India,NaN,NaN,Senior / Lead,General / IT,"Python, Excel, Power Bi, Reporting, Dashboard,...",2026-07-20
4,Data Analyst Intern,CLUSTOR COMPUTING,Shine,Full–time,Through Publisher,False,"Nagpur, Maharashtra",Nagpur,Maharashtra,Intern,General / IT,"Python, Sql, Excel, Power Bi, Tableau, Dashboa...",2026-07-20

In [60]:
df['job_location'].value_counts()

job_location
India                  130
Anywhere                12
Nagpur, Maharashtra      4
Kora, Maharashtra        1
Name: count, dtype: int64

In [61]:
df['job_city'].value_counts()

job_city
Nagpur    4
Kora      1
Name: count, dtype: int64

In [63]:
df['job_location'] = df['job_location'].replace('Anywhere', 'Pan India')

In [64]:
df['job_location'] = df['job_location'].replace('Nagpur, Maharashtra', 'India')

In [65]:
df['job_location'] = df['job_location'].replace('Kora, Maharashtra', 'India')

In [66]:
df['job_location'].value_counts()

job_location
India        135
Pan India     12
Name: count, dtype: int64

In [67]:
df = df.drop(columns=['job_city', 'job_state'], errors='ignore')

In [68]:
df.head()

,job_title,employer_name,job_publisher,job_employment_type,Job_aplication_procedure,job_is_remote,job_location,job_level,job_domain,job_description_keywords,job_posted_date
0,Data Analyst Lead,Jero Technologies,Shine,Full–time,Through Publisher,False,India,Senior / Lead,General / IT,"Python, Sql, Excel, Team, Skills, Strong, Expe...",2026-07-22
1,Data Analyst Fresher,Apex Engineering Solutions,BeBee,Full–time,Through Publisher,False,India,Fresher,General / IT,"Python, Sql, Excel, Power Bi, Tableau, Reporti...",2026-07-20
2,Senior Data Analyst,Walr,Walr,Full–time,Through Publisher,False,India,Senior / Lead,General / IT,"Python, Excel, Analytics, Insights, Working, T...",2026-07-20
3,Data Analyst – Avp,1203 Barclays Global Serv. Cent,Workday,Full–time,Through Publisher,False,India,Senior / Lead,General / IT,"Python, Excel, Power Bi, Reporting, Dashboard,...",2026-07-20
4,Data Analyst Intern,CLUSTOR COMPUTING,Shine,Full–time,Through Publisher,False,India,Intern,General / IT,"Python, Sql, Excel, Power Bi, Tableau, Dashboa...",2026-07-20

In [70]:
df.duplicated().sum()

np.int64(2)

In [71]:
df[df.duplicated(keep=False)]

,job_title,employer_name,job_publisher,job_employment_type,Job_aplication_procedure,job_is_remote,job_location,job_level,job_domain,job_description_keywords,job_posted_date
14,Data Analyst (0 To 1 Year Experience),Jobaaj Com,BeBee,Full–time,Through Publisher,False,India,Data Analyst,General / IT,"Sql, Excel, Power Bi, Tableau, Dashboard, Insi...",2026-07-18
30,Jr Data Analyst,Veracity Software,Indeed,Full–time,Through Publisher,True,Pan India,Data Analyst,General / IT,"Sql, Power Bi, Insights, Team, Skills, Support...",NaT
34,Data Analyst (0 To 1 Year Experience),Jobaaj Com,BeBee,Full–time,Through Publisher,False,India,Data Analyst,General / IT,"Sql, Excel, Power Bi, Tableau, Dashboard, Insi...",2026-07-18
50,Jr Data Analyst,Veracity Software,Indeed,Full–time,Through Publisher,True,Pan India,Data Analyst,General / IT,"Sql, Power Bi, Insights, Team, Skills, Support...",NaT

In [72]:
df = df.drop_duplicates()

In [73]:
df.duplicated().sum()

np.int64(0)

In [74]:
df.isnull().sum()

job_title                    0
employer_name                0
job_publisher                0
job_employment_type          0
Job_aplication_procedure     0
job_is_remote                0
job_location                 0
job_level                    0
job_domain                   0
job_description_keywords     0
job_posted_date             49
dtype: int64

In [79]:
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'], errors='coerce')


mean_date = df['job_posted_date'].mean()
mean_date

Timestamp('2026-07-07 13:15:00')

In [80]:
df['job_posted_date'].fillna(mean_date)

0     2026-07-22 00:00:00
1     2026-07-20 00:00:00
2     2026-07-20 00:00:00
3     2026-07-20 00:00:00
4     2026-07-20 00:00:00
              ...
142   2026-07-07 13:15:00
143   2026-06-24 00:00:00
144   2026-07-09 00:00:00
145   2026-07-09 00:00:00
146   2026-07-07 13:15:00
Name: job_posted_date, Length: 145, dtype: datetime64[ns]

In [83]:
df.isnull().sum()

job_title                    0
employer_name                0
job_publisher                0
job_employment_type          0
Job_aplication_procedure     0
job_is_remote                0
job_location                 0
job_level                    0
job_domain                   0
job_description_keywords     0
job_posted_date             49
job_posted                  49
dtype: int64

In [84]:
df.head()

,job_title,employer_name,job_publisher,job_employment_type,Job_aplication_procedure,job_is_remote,job_location,job_level,job_domain,job_description_keywords,job_posted_date,job_posted
0,Data Analyst Lead,Jero Technologies,Shine,Full–time,Through Publisher,False,India,Senior / Lead,General / IT,"Python, Sql, Excel, Team, Skills, Strong, Expe...",2026-07-22,2026-07-22
1,Data Analyst Fresher,Apex Engineering Solutions,BeBee,Full–time,Through Publisher,False,India,Fresher,General / IT,"Python, Sql, Excel, Power Bi, Tableau, Reporti...",2026-07-20,2026-07-20
2,Senior Data Analyst,Walr,Walr,Full–time,Through Publisher,False,India,Senior / Lead,General / IT,"Python, Excel, Analytics, Insights, Working, T...",2026-07-20,2026-07-20
3,Data Analyst – Avp,1203 Barclays Global Serv. Cent,Workday,Full–time,Through Publisher,False,India,Senior / Lead,General / IT,"Python, Excel, Power Bi, Reporting, Dashboard,...",2026-07-20,2026-07-20
4,Data Analyst Intern,CLUSTOR COMPUTING,Shine,Full–time,Through Publisher,False,India,Intern,General / IT,"Python, Sql, Excel, Power Bi, Tableau, Dashboa...",2026-07-20,2026-07-20

In [85]:
df = df.drop(columns=['job_posted'])

In [86]:
df.head()

,job_title,employer_name,job_publisher,job_employment_type,Job_aplication_procedure,job_is_remote,job_location,job_level,job_domain,job_description_keywords,job_posted_date
0,Data Analyst Lead,Jero Technologies,Shine,Full–time,Through Publisher,False,India,Senior / Lead,General / IT,"Python, Sql, Excel, Team, Skills, Strong, Expe...",2026-07-22
1,Data Analyst Fresher,Apex Engineering Solutions,BeBee,Full–time,Through Publisher,False,India,Fresher,General / IT,"Python, Sql, Excel, Power Bi, Tableau, Reporti...",2026-07-20
2,Senior Data Analyst,Walr,Walr,Full–time,Through Publisher,False,India,Senior / Lead,General / IT,"Python, Excel, Analytics, Insights, Working, T...",2026-07-20
3,Data Analyst – Avp,1203 Barclays Global Serv. Cent,Workday,Full–time,Through Publisher,False,India,Senior / Lead,General / IT,"Python, Excel, Power Bi, Reporting, Dashboard,...",2026-07-20
4,Data Analyst Intern,CLUSTOR COMPUTING,Shine,Full–time,Through Publisher,False,India,Intern,General / IT,"Python, Sql, Excel, Power Bi, Tableau, Dashboa...",2026-07-20

In [87]:
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'], errors='coerce')


mean_date = df['job_posted_date'].mean()
mean_date

Timestamp('2026-07-07 13:15:00')

In [88]:
df['job_posted_date'].fillna(mean_date)

0     2026-07-22 00:00:00
1     2026-07-20 00:00:00
2     2026-07-20 00:00:00
3     2026-07-20 00:00:00
4     2026-07-20 00:00:00
              ...
142   2026-07-07 13:15:00
143   2026-06-24 00:00:00
144   2026-07-09 00:00:00
145   2026-07-09 00:00:00
146   2026-07-07 13:15:00
Name: job_posted_date, Length: 145, dtype: datetime64[ns]

In [89]:
df.isnull().sum()

job_title                    0
employer_name                0
job_publisher                0
job_employment_type          0
Job_aplication_procedure     0
job_is_remote                0
job_location                 0
job_level                    0
job_domain                   0
job_description_keywords     0
job_posted_date             49
dtype: int64

In [90]:
df['job_posted_date'] = df['job_posted_date'].fillna(mean_date)

In [91]:
df.isnull().sum()

job_title                   0
employer_name               0
job_publisher               0
job_employment_type         0
Job_aplication_procedure    0
job_is_remote               0
job_location                0
job_level                   0
job_domain                  0
job_description_keywords    0
job_posted_date             0
dtype: int64

In [92]:
df.to_excel('India_DA_Clean_Data.xlsx', index=False)